# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='phone_numbers',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='contact',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='cellphone',
            field=models.CharField(default=1, help_text='Número de telefone. Preencha apenas com númreos.', max_length=15, verbose_name='Telefone Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(help_text='Número de telefone. Preencha apenas com númreos.', max_length=15, null=True, verbose_name='Teledone Fixo'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
