# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='creation date'),
        ),
    ]
