# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 22:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nome completo do Produto', max_length=100, verbose_name='Nome do produto')),
                ('stock_quantity', models.PositiveIntegerField(help_text='Quantidade do produto em estoque', verbose_name='Quandtidade do produto')),
                ('price', models.FloatField(help_text='Preço atual do produto', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Preço do produto')),
                ('weight', models.FloatField(default=0, help_text='Peso do produto atual', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Peso do produto')),
                ('width', models.IntegerField(default=0, help_text='Largura da Imagem', verbose_name='Largura da Imagem')),
                ('height', models.IntegerField(default=0, help_text='Altura da Imagem', verbose_name='Altura da Imagem')),
                ('illustration', models.ImageField(height_field='height', help_text='Ilustração', upload_to='', verbose_name='Imagem', width_field='width')),
            ],
            options={
                'ordering': ('product_name', 'category_id', 'stock_quantity', 'price'),
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Nome da categoria de produtos', max_length=100, verbose_name='Categoria de Produto')),
            ],
            options={
                'verbose_name': 'Categoria de Produtos',
                'verbose_name_plural': 'Categorias de produtos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
    ]
