# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nome completo do Produto', max_length=100, verbose_name='Nome do produto')),
                ('stock_quantity', models.IntegerField(help_text='Quantidade do produto em estoque', verbose_name='Quandtidade do produto')),
                ('price', models.IntegerField(help_text='Preço atual do produto', verbose_name='Preço do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('product_name', 'category_id', 'stock_quantity', 'price'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Nome da categoria de produtos', max_length=100, verbose_name='Categoria de Produto')),
            ],
            options={
                'verbose_name': 'Categoria de Produtos',
                'verbose_name_plural': 'Categorias de produtos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
    ]
