# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PAD', 'Anuncio'), ('STD', 'Padrao')], default='Padrao', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(help_text='Quantidade do produto em estoque', verbose_name='Quantidade do produto'),
        ),
    ]
