# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0, help_text='Altura da Imagem', verbose_name='Altura da Imagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='illustration',
            field=models.ImageField(default='default_product.jpg', height_field='height', help_text='Ilustração', upload_to='', verbose_name='Imagem', width_field='width'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, help_text='Peso do produto atual', verbose_name='Peso do produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0, help_text='Largura da Imagem', verbose_name='Largura da Imagem'),
        ),
    ]
