# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PAD', 'Anuncio'), ('STD', 'Padrao')], default='Padrao', max_length=3),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='father_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=500, help_text='Altura da Imagem', verbose_name='Altura da Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(help_text='Quantidade do produto em estoque', verbose_name='Quantidade do produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(default=500, help_text='Largura da Imagem', verbose_name='Largura da Imagem'),
        ),
    ]
