# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171001_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=500, help_text='Altura da Imagem', verbose_name='Altura da Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(default=500, help_text='Largura da Imagem', verbose_name='Largura da Imagem'),
        ),
    ]
