# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171026_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='father_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to='products.ProductCategory'),
        ),
    ]
