# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170922_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='illustration',
            field=models.ImageField(height_field='height', help_text='Ilustração', upload_to='', verbose_name='Imagem', width_field='width'),
        ),
    ]
